lint:
	flake8

venv:
	virtualenv --python=python3 venv
	@echo
	@echo "Run this command to activate environment:"
	@echo "     source venv/bin/activate"
	@echo

requirements:
	pip install -r requirements.txt

